### ISSUE TITLE
Active pull request are not showing 

### ISSUE THREAD

**Issue by orzelek12** [sierpinski/Blitz#34] opened 2019-06-28 13:49 UTC
Pull Request Count is alway 0 and non of the PRs are showing even that there are bunch of them assigned to me and I own a couple PR. Same thing is happening on different project in azure.

My workmates have the same issue. Web browser we are using is Chrome
I noticed that following steps are fixing the issue but only for a short period of time: 
 Developer Tools > Application > Storage (on the left) > Clear Local Storage & Session Storage

**Comment by karlingen** [comment] 2019-06-28 17:27
@orzelek12 try the latest package! https://github.com/sierpinski/Blitz/blob/master/sierpinski.blitz-allpulls-extension-1.0.41.vsix

**Comment by sierpinski** [comment] 2019-06-28 17:29
Thanks for reporting this. I had an outstanding PR request with a bug fix by @karlingen for the new repo filtering option and I was just resigning from my job yesterday so I didn't have a chance to work it. Hopefully the new version will fix the issue. I just pushed it out, so let me know if you are still having issues.

**Comment by orzelek12** [comment] 2019-07-01 08:03
@karlingen I tried 1.0.41 and looks like the issue is resolved.
When I went to Options and selected all repos the PRs started to show up.
On version 1.0.40 there was no repos in Repository dropdown so it was probably the source of the problem. 
Now u need to select all repos to show ur PRs so why cant u just select all items in that dropdown by default ? Every time I close AzureDev ops and open it again I need to select all repos to show my PRs

**Comment by karlingen** [comment] 2019-07-01 12:09
@orzelek12 Yes, that is the intended behaviour. 
The reason why you have to re-select the repos is because of limitations in `localStorage` and `<iframe>`. 

A fix for this is included in this PR: https://github.com/sierpinski/Blitz/pull/35

**Comment by sierpinski** [comment] 2019-07-03 20:58
@orzelek12 are your issues resolved now? I want to know before we close the issue.

**Comment by orzelek12** [comment] 2019-07-09 12:08
@sierpinski yep, close the issue ;)

**Comment by sierpinski** [comment] 2019-07-09 17:54
Thanks @orzelek12

**Closed as completed by sierpinski** 2019-07-09 17:54 UTC
Labels: bug, enhancement
